### ISSUE TITLE
Cache file is not created nor used when empty and present

### ISSUE THREAD

**Issue by almereyda** [dim13/gone#12]
Running gone says

    2019/03/20 13:04:53 open /home/username/.cache/gone.gob: no such file or directory

Manually creating the directory did not help, neither did touching the file.

```
$ mkdir -p /home/username/.cache/
$ gone
2019/03/20 13:04:53 open /home/username/.cache/gone.gob: no such file or directory
$ touch .cache/gone.gob
$ gone
2019/03/20 13:05:07 EOF
```

This means all records of gone are lost when the process is terminated.

**Comment by dim13** [comment]
On first run of application this file does not exist, and this message is totally fine. Ignore it.
The file will be created automatically, as gets updated every minute (as per default). You don't have to create it manually.
